### ISSUE TITLE
Commit #64 Breaks Ubuntu install.  0.2.0 release works however.

### ISSUE THREAD

**Issue by cleancoindev** [digital-asset/ex-bond-issuance#76] opened 2020-01-08 03:48 UTC
Installing the primary master branch results in many breaking errors and bugs in the commit https://github.com/digital-asset/ex-bond-issuance/commit/c95dcdf2099803ef930d04aa980be0b6f1c38e81

The issue is this commit.  You approved its changes to the main master.  WHY?

It breaks ubuntu install due to bad calls and bad coding of python into it.  It cannot be installed in this state.

I installed 0.2.0 release and it works fine.  The breaking change occurs between that release and the commit 64 code.

My request is that you revert the master away from that breaking change of commit #64 or fix the broken code.

How can this be fixed, how would you prefer to fix it?

**Comment by richardkapolnai-da** [comment] 2020-01-08 11:33
Thanks for reporting this issue. The mentioned change adds a workaround to use the finlib as a package because we don't have a DAR marketplace yet.

I tried quickly the app with a few choices and apparently it works on my box. Could you specify the issues you ran into? We need to be able to reproduce them on our side to be able to fix them.

**Comment by cleancoindev** [comment] 2020-01-08 20:46
Please list the exact versions of the dependencies you are using?  {What is
your dev environment and version of Ubuntu etc?}

I will try with your exact settings and see if it works on my end.

Thanks!

**Comment by richardkapolnai-da** [comment] 2020-01-09 09:31
I tried on Ubuntu 18.04 with both python 3.6.9 and 2.7.17 and didn't see any issue.

If you could describe the issue you experience and your devenv, we could reproduce it and hopefully fix it. Thanks.

**Comment by cleancoindev** [comment] 2020-01-09 19:47
Ok I'll test that configuration out.

Hey is this system fully put together so that it would allow further than
just the bond being issued in the system or is that the full extent?

Also, I am curious if you are busy mid-feb?  I am creating a real world use
macroeconomic system for carbon credits due to a charity's work in removal
of pollution.

They plan to bill globally so are setting up a system to do so.

I am seeking other people who may be interested in attending the ETH
hackathon in Denver on Feb 14th.  {there's a speed dating event for single
people there}

Don't know if you are interested but I would love to have a 3rd member to
the team for the hackathon...  Myself and Gary are decent coders but
certainly not experts..we could really use some help for our project and
the hackathon.

Would you consider working with my charity on this project?  The income
coming from it later in the year/next year will be very good...

I am not sure how easy it is for you to get to Denver....Please let me know
on the hackathon...

But if not, would you consider joining the project and helping us get
through tough parts if we run into challenges or if you want, be more
involved than this?

I am creating bonds for  the use in tracking global debt and credit for
carbon mitigation at the global scale, its a large accounting challenge but
this is PRECISELY what blockchain was made for.

**Comment by cleancoindev** [comment] 2020-01-09 19:51
As for my config I tried both on Ub 16 and 14 and same issues would occur.
It always had to do with the python calls trying to execute the
executable and failing.

I think its due to earlier systems.  Maybe it doesnt work on prior to 18?
I did verify however that prior to the DAR, the 14 and 16 versions will
work but NOT via docker.

It has issues running the bots and the smart contract roles do not show
up....if run in standalone however, it works on 16 just fine.

**Comment by richardkapolnai-da** [comment] 2020-01-10 11:11
I tried on Ubuntu 16.04 with Docker and everything seemed fine. Please make sure you installed DAML properly and `daml` is in your path (https://docs.daml.com/getting-started/installation.html). If you experience any troubles, please send the exact output and the commands you entered for reproduction.

Bond issuance is mainly about simulating the auction process during a bond issuance. You can find the basic scenarios on the Readme.

If you have any further question, please reach out to us on our public Slack channel https://hub.daml.com/slack/ .

Thanks for the cooperation invitation though. I suggest other channels than this Github issue this kind of discussion. :)

Please let us know if you run into any problem.

**Comment by cleancoindev** [comment] 2020-01-12 02:21
When i was doing it last time it would not pull up the Role Actions of the
issuer.  When i ran the same install in standalone it worked fine.

When i ran it the first time it would work up to the point I needed to
issue the bond to get permissions.  Not sure if i was doing it right but i
would not see the bond in the list of the approver profile.

Anyhow, I will attempt to install it from docker on 16 again to see what
errors i run into and log my installation process to get you exactly what I
did and see if it breaks again when it tries to make the DAR.

Says cannot run 'exec' command basically.  syntax is supposed to be python
in the json file i think not exec but not sure will redo to see.

Sorry about the communication about the hackathon on this channel i
momentarily forgot this was an open forum reply.

May I email you about the project?  I have a link I can send you about the
project for the denver ETH event.

**Comment by richardkapolnai-da** [comment] 2020-01-13 18:21
I also had this problem when I forgot to set the `PATH` to include the `daml` executable, so the Python script could not launch the DAML compiler. Please make sure you enabled it, maybe also `export PATH` and double check you can launch `daml --help` from a new shell.

(Personally I won't be able to go Denver for the event, so I suggest using other channels to find team members.)

**Comment by richardkapolnai-da** [comment] 2020-01-29 09:49
Closing because could not reproduce the issue.

**Closed by richardkapolnai-da** 2020-01-29 09:49 UTC
